# Generated by Django 5.1.1 on 2025-02-22 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("hire_flag", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="CandidateEducation",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("dateRage", models.CharField(max_length=255)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="candidates.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CandidateJob",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("ocupation", models.CharField(max_length=255)),
                ("dateRange", models.CharField(max_length=255)),
                ("skills", models.CharField(max_length=255)),
                ("current_job", models.BooleanField(default=False)),
                ("occupation_title", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="candidates.candidate",
                    ),
                ),
            ],
        ),
    ]
