# Generated by Django 5.1.1 on 2025-02-22 17:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0002_alter_candidateeducation_daterage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidateeducation",
            old_name="dateRage",
            new_name="dateRange",
        ),
    ]
