# Generated by Django 5.1.1 on 2025-02-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0003_rename_daterage_candidateeducation_daterange"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatejob",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="candidatejob",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
