# Generated by Django 5.1.1 on 2025-02-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0004_alter_candidatejob_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidatejob",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
