# Generated by Django 5.1.1 on 2025-02-22 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0005_alter_candidatejob_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidateeducation",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="educations",
                to="candidates.candidate",
            ),
        ),
        migrations.AlterField(
            model_name="candidatejob",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="candidates.candidate",
            ),
        ),
    ]
